# Generated by Django 5.0.6 on 2024-05-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_img',
            field=models.ImageField(default=1, height_field=100, upload_to='', width_field=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
