# Generated by Django 5.0.6 on 2024-05-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_answer_answer_img_alter_test_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_img',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(to='tests.question'),
        ),
    ]
