# Generated by Django 5.0.6 on 2024-05-30 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_testresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_connect',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='tests', to='tests.question'),
        ),
    ]
