# Generated by Django 5.0.6 on 2024-06-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
